# Ingot /var: btrfs state partition (journal, /var/lib/etc).
# PARTUUID is embedded in the UKI's kernel command line (root=).
[Partition]
Type=var
UUID=501347aa-775a-5736-8da3-2a9977c820ec
Label=var
Format=btrfs
SizeMinBytes=4G
SizeMaxBytes=4G
